# Generated by Django 5.1.3 on 2024-12-01 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movielist_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='movie_id',
            new_name='item_id',
        ),
        migrations.AlterUniqueTogether(
            name='movielist',
            unique_together={('user', 'item_id')},
        ),
    ]
